### PR TITLE
add hook to allow for custom value unboxing

### PR DESCRIPTION
**Pull request by andimarek**
This PR adds a general ValuUnboxer hook which lets you implement a custom logic for unboxing values. The default impl unboxes only java.lang.Optional.

### CODE REVIEW

**Comment by sean-brandt** [comment]
While a bit more intrusive a change than #1582 ( even considering that it is my PR ) obviously this works as well. 

I'm not personally convinced that the ServiceLoader approach is too much cognitive dissonance, but don't have any concerns that this will address the need I was trying to fill with #1582

**Comment by andimarek** [comment]
@sean-brandt  you are right: it is a more intrusive change, but we are happy to pay this price for more consistency for our users.

**Comment by kaqqao** [comment]
Just a thought, but why not go for a more general solution for converting/adapting values and then implement unboxing optionals in terms of that? Where I come from (generating GraphQL schemas dynamically), such a solution would be widely applicable. I have a similar custom solution in place already.
As it stands, the current approach solves a highly specialized problem only at the expense of a rather intrusive change...

**Comment by andimarek** [comment]
this hook actually allows you to "unbox" any value. So it that sense it is a general solution. Will try to make the naming more clear

**Pull request merged**
