### PR TITLE
fix variable directive

### PR DESCRIPTION
**Pull request by dugenkui03**
make directives to be children of VariableDefinition.

### CODE REVIEW

**Comment by andimarek** [comment]
thanks, you are right, this is missing at the moment.

Can you please add  directives to the `getNamedChildren` method in `VariableDefinition`? thanks

**Comment by dugenkui03** [comment]
> thanks, you are right, this is missing at the moment.
> 
> Can you please add directives to the `getNamedChildren` method in `VariableDefinition`? thanks

Thanks for point out the omission.

**Comment by dugenkui03** [comment]
The RP haven been change and squashed into a single commit.

**Comment by dugenkui03** [comment]
> I think the Copy Constructor of the Builder needs also to deal with directives.

The RP haven been change  and make VariableDefinition implement DirectivesContainer.

**Comment by andimarek** [comment]
thanks a lot

**Pull request merged**
