### PR TITLE
#427 - NullValue support plus "provided null" versus "not provided" null values

### PR DESCRIPTION
**Pull request by bbakerman**
This is an early push for demostration purposes

### CODE REVIEW

**Comment by andimarek** [comment]
The current behaviour is as following:

```graphql
type foor(bar: String) {
...
}
```
```graphql
foor 
```
-> Arguments Map contains key "bar" with value `null`.

**Comment by kaqqao** [comment]
@andimarek Even though I find this approach more cumbersome to use (requires checking for this special value in addition to checking for nulls), I think it is the correct approach. It's very explicit and unambiguous, and that is IMHO the most important metric for a low-level library.

**Comment by andimarek** [comment]
@kaqqao yes,

I am also not totally happy with it, because if you allow `null` values, now you have to check for an additional type (is it == `GraphQLNullValue.NULL`).

Which is a breaking change, when I think about it: If someone upgrades `graphql-java` and allows `null` values, suddenly there can be a new value in the `arguments` Map, which can't be cast to the expected value (e.g. String or boolean).
🤔  Not sure this is good.

**Comment by bbakerman** [comment]
BTW we can split this PR into 2 - the ability to specify`null` as a literal value and the "absence of null" at runtime.

The first has some value just in being able to do literal specifications

The absence of null is valuable for the mutation reasons

**Comment by bbakerman** [comment]
When I started this PR I first had the idea of a special sentinal value eg: `GraphQLNullValue.NULL`

But while explicit, its really Java unnatural.  Its easier in javaScript since they have 'undefined' and 'null' values for this use case (sort of).

I was thinking about it from the consumers point of view and thats the DataFetcher

            Object get(DataFetchingEnvironment environment) {
                   Map<String,Object> args = environment.getArguments()
                   Map<String,Object> argObject = arg.get("ComplexThing");
                   
             }

The complex object is going to be a Map and hence trying to work out if "bar" is present or not can be done via `argObject.contains("subFIeld")`

     if (argObject.contains("subField") {
          updateSubField(argObject.get("subField"))

The proposed code would then be more like

     Object subValue  = argObject.get("subField");
     if (! GraphQLNullValue.NULL.equals(subValue))
          updateWithSubField(subValue)


It just feels a lot less expected.  Its precise but its less natural.

Either way the change is a behaviour breaking change since existing code cant know that GraphQLNullValue.NULL is possible or that null handling has changed.

**Comment by andimarek** [comment]
@bbakerman I agree that it would be unnatural and in case of a complex `InputObject` your idea feels nice, but what about `foo` vs `foo(bar: null)` (my example from above)? How do you handle that?

**Comment by andimarek** [comment]
and btw: I would prefer not to add that topic to 3.0.0 ... it is already a lot. We should aim for 4.0.0 for that change.

**Comment by andimarek** [comment]
just so that we don't forget to think about that case too:

this change also allows `null` in lists: This is a valid query:

```graphql
someField(value: ["Value1", null, "Value3"]
```

**Comment by kaqqao** [comment]
@andimarek I don't I'm getting you about `foo` vs `foo(bar: null)`. Won't one result in an empty map, and the other in a map with key `bar` and value `null`?

**Comment by andimarek** [comment]
@kaqqao that is exactly the problem: It won't:

`foo` results in an argument map with `"bar"`-> `null`. This is the current behaviour: **`bar` is never missing**

As you can see there is no way to differentiate between `foo` and `foo(bar: null)`: Under the constraint that we do not wan't to change the current behaviour both would result in `"foo"` -> `null`.

**Comment by bbakerman** [comment]
Have a look at : https://github.com/facebook/graphql/blob/master/spec/Section%203%20--%20Type%20System.md

And the Input Coercion part of it : 







> For each field of the input object type, if the original value has an entry with the same name, and the value at that entry **is a literal value or a variable which was provided a runtime value**, an entry is added to the result with the name of the field.

The value of that entry in the result is the outcome of input coercing the original entry value according to the input coercion rules of the type declared by the input field.

Following are examples of Input Object coercion for the type:

```
input ExampleInputObject {
  a: String
  b: Int!
}
```

```
Original Value	          Variables	Coerced Value
{ a: "abc", b: 123 }   {null}	        { a: "abc", b: 123 }
{ a: 123, b: "123" }	 {null}	        { a: "123", b: 123 }
{ a: "abc" }	         {null}	        Error: Missing required field {b}
{ a: "abc", b: null }	 {null}	        Error: {b} must be non-null.
{ a: null, b: 1 }	         {null}	        { a: null, b: 1 }
{ b: $var }	         { var: 123 }	{ b: 123 }
{ b: $var }	         {}	                Error: Missing required field {b}.
{ b: $var }	         { var: null }	Error: {b} must be non-null.
{ a: $var, b: 1 }	 { var: null }	{ a: null, b: 1 }
{ a: $var, b: 1 }	 {}	                { b: 1 }
```

> Note: there is a semantic **difference** between the input value explicitly declaring an input field's value as the value {null} vs having not declared the input field at all.

So I think for 4.0 it would be right thing to do to move towards "spec" and use the absence of the field in the map to indicate that absence and presence in the map (with possible null value) to indicate present with some value (which maybe null or not)

Using a sentinel GraphqlNullValue is a mistake I think.  Saving this change for 4.0 say because of the breaking runtime behavior

**Comment by bbakerman** [comment]
BTW - there is minor runtime breaking behaviour in adding 'null literal' support

Technically `foo(arg : null)` will today be parsed as a enum and hence we when add the null keyword support that will no longer work./

I think this is really minor since it would require some one to be accepting a enum and the word `null` being one of the enum values.  I think we can ignore that as being bad

**Comment by andimarek** [comment]
After talking with @bbakerman we came to the following solution:

It is the best for the future to map "not provided" to "no key in map" and `null` to a java map with a key and java `null` as value. This is very straight forward and intuitive.

**But**:
As mentioned before it breaks the current behaviour for `foo` (see my example above): After that change there would be no `"bar"` key in the `arguments` map.

**Legacy Option:**
This is a very subtle change and it might break stuff. To adress that we will add a `legacy arguments` option in 4.0.0, which is turned on by default: this flag keeps the current behaviour and results in  the same `arguments` map for `foo` and `foo(bar: null)`. 

This option will be removed in version 5.

The special `Enum` case (https://github.com/graphql-java/graphql-java/pull/434#issuecomment-301370721) will just be documented.

**Comment by kaqqao** [comment]
While the missing key vs the current key-with-null is indeed a subtle change, I don't think it's likely to cause any damage. Currently the key is always present so there's really no reason anyone would be checking for its presence (the part that is changing), and `args.get(missingKey)` returns `null` anyway.

**Comment by andimarek** [comment]
@kaqqao I agree it is very subtle change. But especially with these changes we try to be empathic with our users.

**Comment by andimarek** [comment]
These tests document the current behaviour: https://github.com/graphql-java/graphql-java/commit/d8bfa00494548e2259a2851cd21a70a3519bf962

The more I think about, the more I am convinced that we don't need a legacy option flag: it is a very subtle change, but I believe it would not really break anything. 

To break something the code would need to relay on the existing of a key in a map being null.
But the following would be still okay:
```java
if (arguments.get("bar") != null) ...
```
for a query ``{foo}``.  @bbakerman

**Comment by kaqqao** [comment]
This was exactly my point in the previous message. Unless the code does `arguments.contains("key")`, it will be fine. And there's no reason to ever check `contains` as it would always be true... So the change is highly unlikely to cause any damage.

**Comment by andimarek** [comment]
@kaqqao Yes, you right. Didn't want to neglect your comment ... just needed some time let that sink in.

**Comment by bbakerman** [comment]
Damn I have buggered this branch right up. I am going to throw it away and start again...with a TDD approach.

And I have the right PR this time

**Comment by bbakerman** [comment]
And now I see that tests have already been added....  missed that sorry.

Anyway I am starting a new branch either way to make sure I am 3.0 clean

**Pull request closed without merging**
