### PR TITLE
Number to primitive types

### PR DESCRIPTION
**Pull request by jackielii**
I'm using google.gson to de-serialise variables etc, and it puts everything as double. If my variable type is Int, it would return null.

### CODE REVIEW

**Comment by andimarek** [comment]
I am not sure about this change: When we convert a Number to Int we might loose something. (e.g. 3,14 -> 3) 

What do you think? (See http://facebook.github.io/graphql/#sec-Int)

**Comment by yrashk** [comment]
According to that spec, there could be nothing but an in integer as an input for Int. GSON doesn't make a best guess about number's type. 

We can either handle this by coercing numbers to ints (as per this PR) or we can stipulate that whatever deserialization algorithm is used, it needs to return ints as ints. GSON with custom a *type adaptor* might be a solution for this (http://stackoverflow.com/questions/15507997/how-to-prevent-gson-from-expressing-integers-as-floats, http://stackoverflow.com/questions/24926786/make-gson-deserialize-numbers-to-integers-or-doubles, etc.)

This is all about where do we set the validation boundary.

**Comment by danielkwinsor** [comment]
I want to leave Int an int and let deserializers do the conversion.

The set of known implementors of Number include BigInteger, BigDecimal, and a few other notables like Byte, Character, and Short.

I've already run into BigIntegers and BigDecimals, for which I created custom scalars, as the spec suggests when dealing with numeric integers larger than 32 bits.

Speaking of this, I have made custom scalars for BigInteger, BigDecimal, Byte, Character, Short.  Let me know if you'd like them included in graphql-java.

**Comment by yrashk** [comment]
I'd love to see those scalars in. If not in the core library, then in a compendium one

**Comment by danielkwinsor** [comment]
Will do, but looks like master and 2.0.0 have diverged such that my code no longer works (graphql.langauge.IntValue now returns BigInteger).

**Comment by exbe** [comment]
Is there any test code, which can help to reproduce this issue? I can't recall any issues with jackson.

**Comment by dminkovsky** [comment]
This issue https://github.com/graphql-java/graphql-java/issues/259 is the same thing. I closed it because I don't think the built-in scalars should account for this. Writing a scalar with the exact behavior you want is easy. And could be contributed even as a side-project. 

But, if this is an issue that affects many people, maybe it should be included? I don't know.

**Comment by bbakerman** [comment]
I think this issue between "strict correctness" and developer expectations of "least surprise" are going to keep catching the code out.

I know I got caught out using GSON and pumping it into the graphql lib and so will others.

At a minimum we should update the readme with examples about GSON etc... 

I would argue the library should co-erce much like JS would do.  And then if you want strict Scalars you could have a graphql.strict.Scalars say.

Or we make it strict by default and have graphql.lenient.Scalars

**Comment by dminkovsky** [comment]
Yeah if we're talking least astonishment and we believe this is a common
source of astonishment then we should remove this source of astonishment
despite "correctness".

пн, 30 янв. 2017 г. в 16:31, bbakerman <notifications@github.com>:

I think this issue between "strict correctness" and developer expectations
of "least surprise" are going to keep catching the code out.

I know I got caught out using GSON and pumping it into the graphql lib and
so will others.

At a minimum we should update the readme with examples about GSON etc...

I would argue the library should co-erce much like JS would do. And then if
you want strict Scalars you could have a graphql.strict.Scalars say.

Or we make it strict by default and have graphql.lenient.Scalars

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/graphql-java/graphql-java/pull/105#issuecomment-276197371>,
or mute the thread

**Comment by bbakerman** [comment]
I am putting together a PR for a LenientNumericalScalars if we want it to be strict by default, lenient by choice say

If its decided to reverse this policy, the code can be easily swapped

https://gist.github.com/bbakerman/9bdb1cf835735113b83e16d64547bf49

**Comment by bbakerman** [comment]
This has now been implemented via a lenient approach

**Pull request closed without merging**
