### PR TITLE
1181 Fix null element in InputValueDefinition#getChildren

### PR DESCRIPTION
**Pull request by tsroka**

### CODE REVIEW

**Comment by andimarek** [comment]
@tsroka how did you come across this?

**Comment by andimarek** [comment]
@tsroka could u use the graphql-java formatter (https://github.com/graphql-java/graphql-java/blob/master/graphql-java-code-style.xml) to avoid not needed changes? thanks

**Comment by tsroka** [comment]
@andimarek while working on nadel, i needed to traverse AST using NodeTraverser and got NPE. Will fix formatting,

**Comment by andimarek** [comment]
this should also go into stable 9.x

**Pull request merged**
