### PR TITLE
Add Enum support for directives

### PR DESCRIPTION
**Pull request by AnkBurov**
#1500 
Currently enum types in directives are not supported for some reason. A PR to add support for them.

### CODE REVIEW

**Comment by bbakerman** [comment]
I too want to see enums in introspection.

The challenge we have is that the graphql specification does not define it.

So where do we put them?  I guess we could choose a name that indicates its non spec compliant and then later if the spec adds it then we can also add them there

**Comment by bbakerman** [comment]
We are going to decline this directive.  The code path changed is in fact invalid in and of itself.

That is in the absence of a directive definition, this code base tries to guess a value.  But this is wrong.  Which is why enum and object type are not supported.  We have no way of guessing.

The real fix is that we enforce "having to declare schema directives".  That is if you declare `@foo`then some where else you have declared `directive @foo on ARGUMENT_DEFINITION` first

**Comment by AnkBurov** [comment]
@bbakerman thanks for the answer. Could clarify will `graphql-java` project support enums as arguments in directives? E.g. this:

```
directive @directiveExample (
    enumArguments: [SomeEnum!] = []
) on FIELD_DEFINITION

enum SomeEnum {
    VALUE_1
    VALUE_2
}
```

**Comment by andimarek** [comment]
@AnkBurov yes this is how we will support enums (and everything else): you have to declare the directive.

**Comment by AnkBurov** [comment]
Any specific plans about supporting enums in directive arguments? Because the following schema 
```
directive @directiveExample (
    enumArguments: [SomeEnum!] = []
) on FIELD_DEFINITION

enum SomeEnum {
    VALUE_1
    VALUE_2
}
```
currently is unsupported in `graphql-java` (see #1500) unless the pull request fix is applied.

**Comment by andimarek** [comment]
@AnkBurov this example you mentioned is working: See this comment https://github.com/graphql-java/graphql-java/issues/1500#issuecomment-574921405

**Comment by AnkBurov** [comment]
Yes, I can confirm that this is working. The problem was that the project `graphql-java-tools` (from kickstart guys, not you) under the hood of schema parsing invokes `graphql-java` class `SchemaGeneratorHelper.buildDirective(..)` method that eventually invokes `SchemaGeneratorHelper.buildDirectiveInputType(..)` that throws the error about not supporting enums.

`SchemaGeneratorHelper` is marked as internal API so I guess that's the fault of `graphql-java-tools` for using your project's internal API. Thanks.

**Comment by etheran** [comment]
@AnkBurov how did you work around this issue?  I'm currently facing the same problem and I'm not seeing a way to overcome this without ditching graphql-java-tools at this point, which really isn't possible in my project.
Thanks!

**Comment by AnkBurov** [comment]
@etheran I'm using a fork of the project with this merged pull request https://github.com/AnkBurov/graphql-java/commit/d5429d5aeaaf4204d2f5f820cc2a4819e952ac14 
which I synchronize with an upstream once in a while. 

Other solutions are related with rewriting `graphql-java-tools` to use public API of `graphql-java` instead of an internal one or throw the `graphql-java-tools` out of my projects completely. Neither of options are realistic or applicable to me.

If you face the same issue (which you do) I suggest you to make a fork with similar changes and use it everywhere where you need a combination of `graphql-java-tools` from kickstart guys and `graphql-java`. 

Or you can try to persuade `graphql-java` maintainers to make such changes in the internal part of the API :smile: but it can be a little tricky since they take position `it's internal API, don't want to hear anything wada wada wada`.

**Comment by andimarek** [comment]
@AnkBurov @etheran the original reported issue is fixed: GraphQL Java supports Enums as directive arguments. The original exception also doesn't exist anymore (the whole code sections is changed).

If there is another Issue or something similar please open a new Issue and describe what the problem is.

**Pull request closed without merging**
