### PR TITLE
removed ExecutionContext from DataFetcherEnvironment

### PR DESCRIPTION
**Pull request by bbakerman**
This removes the ExecutionContext from the DataFetcher interface.

This removes the large implementation leak that is in the API.

### CODE REVIEW

**Comment by cmonty** [comment]
@bbakerman We currently use the `ExecutionContext` to pass authorization data to DataFetchers. Is there an alternative implementation for passing this type of per execution context to DataFetchers after this is released?

**Comment by andimarek** [comment]
@cmonty thanks for your feedback: can you give use more details how you use it? Also just to be clear: the `ExecutionContext` is different from `context` in the `DataFetcherEnvironment`. I would expect that you use `context` (which is an `Object`) to pass down authorization data.

Thanks

**Comment by cmonty** [comment]
@andimarek Ah, you're correct. We use `env.getContext()` to pass authorization data, which is the `Object` you described. Sorry for the confusion!

We do use `ExecutionContext` and call `addError` when an exception is thrown.

**Comment by cmonty** [comment]
Awesome, thanks for the information!

**Comment by Salrandin** [comment]
Hi, I have a question about this.  We are trying to update our GraphQL code where we also use ExecutionContext.addError().  In the DataFetcherExceptionHandler implementation we want to catch a few specific exceptions and log them as warnings rather than errors.  It looks like we can still do that but the return for DataFetcherExceptionHandlerResult requires GraphQL errors.  Is there something I can use to convert the regular throwables to GraphQL errors.

**Comment by bbakerman** [comment]
@Salrandin - seae the answer above

Use https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/execution/DataFetcherResult.java

The allows you to send back errors from a data fetcher without throwing an exception.

**Comment by Salrandin** [comment]
I kinda get the solution but does this mean every datafetcher has its own responsibility for handling specific errors?  The reason the implementation worked well was because we could handle it for all the datafetchers which kept our graphql instance uniform.

**Comment by bbakerman** [comment]
You can write your own `graphql.execution.DataFetcherExceptionHandler` if
you want the one handler to be used for all cases

**Comment by kratostaine** [comment]
@bbakerman After this change, is there any way I can add error to the ExecutionContext in my custom dataFetcher other than returning error wrapped in a DataFetcherResult? I was adding error in my custom data fetcher using `environment.executionContext.addError()`. Is there any way around that without changing my dataFetcher to return a DataFetcherResult?

**Comment by David-Java-stack** [comment]
Hi, I implemented Instrumentation and using parameters.getContext() to get authentication , however , since now, getContext() is deprecated , I tried to use getGraphQLContext() instead but it returning empty object , what should I do ?
thx

@Slf4j
@RequiredArgsConstructor
public class RequestLoggingInstrumentation extends SimpleInstrumentation {


    @Override
    public InstrumentationContext<ExecutionResult> beginExecution(
            InstrumentationExecutionParameters parameters) {
        GraphQLServletContext context = parameters.getContext();
        HttpServletRequest request = context.getHttpServletRequest();
        KeycloakSecurityContext keycloakSecurityContext = (KeycloakSecurityContext) 
        request.getAttribute(KeycloakSecurityContext.class.getName());

**Comment by bbakerman** [comment]
> I tried to use getGraphQLContext() instead but it returning empty object

You would be better to raise this question as a discussion item rather than a comment on a 3 year old PR

**Pull request merged**
