### PR TITLE
Add 'compute' family of methods to GraphQLContext

### PR DESCRIPTION
**Pull request by salvoilmiosi**
This will solve https://github.com/graphql-java/graphql-java/issues/3363

### CODE REVIEW

**Comment by bbakerman** [comment]
I am happy to accept this PR but it needs tests.  I know its a simple delegation to the map underneath but lets have a unit test to show that.  Should we change the way it works in the future, we have tests locking in this contract

**Review by bbakerman — CHANGES_REQUESTED** [review]
We need tests for the new methods.  Thanks

**Comment by salvoilmiosi** [comment]
I have added the tests for this change. Thank you.

**Review by bbakerman — APPROVED** [review]
Thanks

**Pull request merged**
