### PR TITLE
Reduce the usage of CompletableFutures in graphql-java - now with objects

### PR DESCRIPTION
**Pull request by bbakerman**
This PR builds on https://github.com/graphql-java/graphql-java/pull/3480 and adds polymorphic waiting on objects value completion

The other PR did not use true polymorphic waiting on objects and hence got a CF for each object type field retrieved (as opposed to scalars / enums / lists and nulls say) but this PR now adds that

### CODE REVIEW

**Comment by bbakerman** [comment]
Ok so I did some profiling of the memory usage in JProfiler

I ran the ComplexQueryBenchmark code in 60 second mode

Now the benchmark does use CF fetching - the complexXXX fields do an async fetch and hence use a CF - but the resultant list values back of objects do not.  The non complex fields are simple materialized objects


* it gets ready but does nothing
* then it runs for 60 seconds and exits
* I had JProfiler memory recording on for 1:10 allocations

Here is master baseline 

``` 
Recorded Objects
Session:	graphql-java-clean [:ComplexQueryBenchmark.main()]
Time of export:	Saturday, March 2, 2024 at 4:11:45 PM Australian Eastern Daylight Time
JVM time:	01:25
 	 
Sorted by: 	Instance Count
Aggregation level: 	Classes
Liveness mode: 	Live Objects
Recording rate: 	1/10 allocations

Name Instance									Count	Size
java.util.LinkedHashMap$Entry						16,915 (12 %)	676 kB
java.util.concurrent.CompletableFuture				16,644 (12 %)	399 kB
java.lang.String									14,836 (10 %)	356 kB
java.lang.Object[ ]									5,111 (3 %)	135 kB
graphql.introspection.Introspection$$Lambda$592.154913348	 3,877 (2 %)	93,048 bytes
graphql.introspection.Introspection$$Lambda$588.1661450720	 3,855 (2 %)	61,680 bytes
com.google.common.collect.ImmutableList$Builder		3,553 (2 %)	85,272 bytes
java.lang.Object									3,059 (2 %)	48,944 bytes
graphql.execution.ExecutionStrategyParameters	 2,932 (2 %)	140 kB
graphql.execution.incremental.DeferredCallContext	 2,886 (2 %)	46,176 bytes
java.util.concurrent.CopyOnWriteArrayList	 2,719 (1 %)	65,256 bytes
graphql.execution.ExecutionStrategyParameters$Builder	 2,710 (1 %)	130 kB
graphql.util.IntraThreadMemoizedSupplier	 2,663 (1 %)

```

and with this change

```
Recorded Objects
Session:	graphql-java [:ComplexQueryBenchmark.main()]
Time of export:	Saturday, March 2, 2024 at 4:11:08 PM Australian Eastern Daylight Time
JVM time:	02:14
 	 
Sorted by: 	Instance Count
Aggregation level: 	Classes
Liveness mode: 	Live Objects
Recording rate: 	1/10 allocations

Name									Instance Count	Size
java.util.LinkedHashMap$Entry	 			33,374 (12 %)	1,334 kB
java.lang.String	 						29,558 (10 %)	709 kB
java.lang.Object[ ]	 						15,683 (5 %)	435 kB
graphql.introspection.Introspection$$Lambda$603.1348904399	 9,755 (3 %)	234 kB
graphql.introspection.Introspection$$Lambda$594.1243935324	 9,719 (3 %)	155 kB
java.util.concurrent.CompletableFuture	 	7,932 (2 %)	190 kB
java.lang.Object	 						7,147 (2 %)	114 kB
graphql.execution.ExecutionStrategyParameters	 7,076 (2 %)	339 kB
graphql.execution.ExecutionStrategyParameters$Builder	 7,074 (2 %)	339 kB
java.util.concurrent.CopyOnWriteArrayList	 7,068 (2 %)	169 kB
graphql.execution.incremental.DeferredCallContext	 6,976 (2 %)	111 kB
graphql.util.IntraThreadMemoizedSupplier	 6,715 (2 %)	161 kB
com.google.common.collect.ImmutableList$Builder	 6,481 (2 %)	155 kB
graphql.execution.FieldValueInfo	 4,126 (1 %)	99,024 bytes
```

Now as you can see - the CF usage is considerable smaller - all the lists and scalars and materialized objects are not wrapped in CFs

Note also

```
graphql.introspection.Introspection$$Lambda$603.1348904399	 9,755 (3 %)	234 kB
graphql.introspection.Introspection$$Lambda$594.1243935324	 9,719 (3 %)	155 kB
```

these are error argument suppliers in a hot path

**Comment by bbakerman** [comment]
master

Capto_Capture 2024-03-02_04-29-29_pm

after

Capto_Capture 2024-03-02_04-30-02_pm


in image view from exported html

I don't know why the data sizes are different - I am guessing because this was based on time and not "number of runs" it managed to run more loops

That said lets concentrate on the % of total - on master CFs make up 12% of objects allocated - on this branch its 2%

**Comment by bbakerman** [comment]
I ran a series of benchmarks on the PRS that make up this progressive change.  I want to make sure its not slower than before.

I know from the above it uses less memory but what happens if its slower say?  Would the trade off be worth it.

Well from the benchmarks below - its no slower and some times a small bit faster.  So when you combine that with significant memory savings - then win!

```
master branch - baseline

======


Benchmark                                                (howManyItems)   Mode  Cnt   Score   Error  Units
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput                5  thrpt    4   2.610 ± 0.259  ops/s
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput               10  thrpt    4   1.308 ± 0.164  ops/s
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput               50  thrpt    4   0.267 ± 0.013  ops/s

IntrospectionBenchmark.benchMarkIntrospectionThroughput             N/A  thrpt    9   0.912 ± 0.080  ops/s
IntrospectionBenchmark.benchMarkIntrospectionAvgTime                N/A   avgt    9   1.104 ± 0.058   s/op

TwitterBenchmark.benchmarkThroughput                                N/A  thrpt    9  82.534 ± 7.060  ops/s
TwitterBenchmark.benchmarkAvgTime                                   N/A   avgt    9   0.013 ± 0.001   s/op

====


async-on-objects branch


Benchmark                                                (howManyItems)   Mode  Cnt   Score    Error  Units
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput                5  thrpt    4   2.608 ±  0.144  ops/s
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput               10  thrpt    4   1.328 ±  0.125  ops/s
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput               20  thrpt    4   0.665 ±  0.070  ops/s

IntrospectionBenchmark.benchMarkIntrospectionThroughput             N/A  thrpt    9   0.890 ±  0.097  ops/s
IntrospectionBenchmark.benchMarkIntrospectionAvgTime                N/A   avgt    9   1.085 ±  0.091   s/op

TwitterBenchmark.benchmarkThroughput                                N/A  thrpt    9  80.932 ± 11.685  ops/s
TwitterBenchmark.benchmarkAvgTime                                   N/A   avgt    9   0.013 ±  0.001   s/op


======


reduce-cf-usage branch

Benchmark                                                (howManyItems)   Mode  Cnt   Score   Error  Units
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput                5  thrpt    4   2.597 ± 0.187  ops/s
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput               10  thrpt    4   1.330 ± 0.165  ops/s
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput               20  thrpt    4   0.672 ± 0.084  ops/s

IntrospectionBenchmark.benchMarkIntrospectionThroughput             N/A  thrpt    9   0.990 ± 0.076  ops/s
IntrospectionBenchmark.benchMarkIntrospectionAvgTime                N/A   avgt    9   1.010 ± 0.047   s/op

TwitterBenchmark.benchmarkThroughput                                N/A  thrpt    9  88.998 ± 5.828  ops/s
TwitterBenchmark.benchmarkAvgTime                                   N/A   avgt    9   0.011 ± 0.001   s/op


=======

reduce-cf-usage-on-objects branch

Benchmark                                                (howManyItems)   Mode  Cnt   Score   Error  Units
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput                5  thrpt    4   2.601 ± 0.094  ops/s
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput               10  thrpt    4   1.325 ± 0.146  ops/s
ComplexQueryBenchmark.benchMarkSimpleQueriesThroughput               20  thrpt    4   0.672 ± 0.064  ops/s

IntrospectionBenchmark.benchMarkIntrospectionThroughput             N/A  thrpt    9   1.192 ± 0.108  ops/s
IntrospectionBenchmark.benchMarkIntrospectionAvgTime                N/A   avgt    9   0.846 ± 0.084   s/op

TwitterBenchmark.benchmarkThroughput                                N/A  thrpt    9  91.368 ± 3.008  ops/s
TwitterBenchmark.benchmarkAvgTime                                   N/A   avgt    9   0.011 ± 0.001   s/op
```

**Comment by dfa1** [comment]
this is very promising approach 🤓I'll be happy to test and to report back as soon as it lands on master!

**Comment by bbakerman** [comment]
@dfa1 - while this has not landed on master - https://github.com/graphql-java/graphql-java/pull/3480 has

This means scalars / enums and lists are not wrapped in CFs.  So you could start some testing now if you like.  While having materialised objects is the end state, I think there is heaps of value in supporting materialised simple values

**Review by andimarek — APPROVED** [review]

**Comment by bbakerman** [comment]
@dfa1 - this is now on master

**Comment by dfa1** [comment]
@bbakerman started testing now after the Easter break. I found a couple of breaking changes in the `ExecutionStrategy`, that maybe should be mentioned in the changelog? Notably:

1) `AbstractAsyncExecutionStrategy.handleResults`: `List<ExecutionResult>` -> `List<Object>` in the signature below:
`protected BiConsumer<List<Object>, Throwable> handleResults(ExecutionContext executionContext, List<String> fieldNames, CompletableFuture<ExecutionResult> overallResult) {
`

2) `ExecutionStrategy.completeValueForObject`: 
`protected Object /* CompletableFuture<Map<String, Object>> | Map<String, Object> */
    completeValueForObject(ExecutionContext executionContext, ExecutionStrategyParameters parameters, GraphQLObjectType resolvedObjectType, Object result) {`

**Comment by bbakerman** [comment]
> Maybe this should be mentioned in the changelog?

Yup - I mention them in a general sense that `ExecutionStrategy` methods have changed but not specific ones.

In fact if we had out time again, `ExecutionStrategy` would not be public API and would be reserved as a implementation class.  The reasoning is its hard to change AND preserve old semantics.  The re-use level is low and the lock cost is too high

**Pull request merged**
