### PR TITLE
Recursive types not being resolved

### PR DESCRIPTION
**Pull request by alexkrebiehl**
Addresses #118 

If we already have a type resolved on the typemap, the resolved type should point to the same instance.

### CODE REVIEW

**Comment by yrashk** [comment]
1. What would be the best and shortest way to model a test case here? 
1. If we address #85 (switch from reference to deep equality), would that help? According to the last comment by @alexkrebiehl on #118, there's an issue with multiple instances of what's effectively one type.

**Comment by alexkrebiehl** [comment]
I'll look at making a test case for this.

As far as reference vs deep equality, I don't think it will help here (at least in my use case).  I'm using graphql-java-annotations and building the schema at runtime, so nodes being created don't know about other nodes that were already created.  If I create two object that reference a type, I'll end up with an instance created for each reference.

Since we actually alter the object when resolving type references, we either need to make sure everything is pointing to the same instance of that object, or we have to resolve type references for all of the duplicates.

I don't think this will help #85 very much, since they are generating types on the fly.  However, this fix did solve my problems with fragment spreads.  Did you still have the fragment issue after the fix in this PR?

**Comment by yrashk** [comment]
I would like to bump this issue up. I think the concern behind it is quite important.

**Comment by yrashk** [comment]
Guys, any objections to merging this PR? It looks like the problem addressed here keeps popping up in different projects and this PR fixes it.

**Comment by danielkwinsor** [comment]
Pr looks ok, if we do it I'll check in my test case.

**Comment by dminkovsky** [comment]
Looks good to me.

Daniel Windsor says he has a test case, if I understood
him correctly. Could add that too as part of another PR. Maybe open an
issue for that if you merge this PR, so we don't forget.

пятница, 26 августа 2016 г. пользователь Yurii Rashkovskii написал:

**Comment by markphilpot** [comment]
I agree with @yrashk -- let's merge this and open an Issue to track adding a test case for it.

**Pull request merged**
