### PR TITLE
multiple interfaces should use ampersand

### PR DESCRIPTION
**Pull request by henryqdineen**
http://facebook.github.io/graphql/draft/#sec-Interfaces

### CODE REVIEW

**Comment by andimarek** [comment]
Thanks for the PR.

Could you please add a test for it? It seems that we don't have a test for multiple Interfaces at the moment, so it is a good moment to create one. You should look at https://github.com/graphql-java/graphql-java/blob/master/src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy for inspiration.

Thanks a lot!

**Comment by andimarek** [comment]
note: we also have https://github.com/graphql-java/graphql-java/blob/1f1377201f89422e81de369ad06574e0f4c73e00/src/main/java/graphql/language/AstPrinter.java#L284 btw: this needs to changed too in order to be consistent.

**Comment by bbakerman** [comment]
Yeah before the spec went public, it was , based.  It still is (because , is whitespace) but this is more idiomatic.

A test would be excellent to ensure we don't regress

**Comment by henryqdineen** [comment]
Thanks guys. I just updated some of the tests so these cases are covered. Sorry I didn't get too creative with the tests.

**Comment by andimarek** [comment]
thanks @henryqdineen

**Comment by henryqdineen** [comment]
Will this be in 8.0?

**Comment by ieugen** [comment]
Looks like it made it https://github.com/graphql-java/graphql-java/commits/v8

**Pull request merged**
