### PR TITLE
Adds arbitrary meta data to the graphql types

### PR DESCRIPTION
**Pull request by bbakerman**
See #183 

This allows arbitrary metadata  to be associated with graphql runtime types.

Directives are probably what IDL people would use but this allows hand coded types to have metadata associated with them.

Perhaps in a future PR would could "runtime wire" in metadata as well but not in this PR

### CODE REVIEW

**Comment by andimarek** [comment]
I get the idea behind it (and we should provide a solution for the underlying problem), but it breaks completely the immutability of the schema objects. I am not sure this is the right way ...

**Comment by kaqqao** [comment]
Once the object is created it _is_ immutable (thanks to the final unmodifiable map)... Seems pretty safe...

**Comment by andimarek** [comment]
@kaqqao you can put whatever you want into the Map and if you put something mutable into the Map and change it later the original graphql object is changed too.

**Comment by kaqqao** [comment]
@andimarek Yup, you're of course right... No good ideas how this can be designed more safely...

**Comment by aschrijver** [comment]
maybe you could use `Map<String, String>` or an immutable `Metadata.get(key)` interface and impls that clone the data..

**Comment by bbakerman** [comment]
>but it breaks completely the immutability of the schema objects.

No it doesnt - I wrap the map in unmodifiableMap() in every case

           this.metadata = metadata == null ? emptyMap() : unmodifiableMap(metadata);

**Comment by andimarek** [comment]
@bbakerman yes we will not solve the general problem here.

But schema objects are immutable today (technically they are only after the schema was created if you use type references, without even before): every object referenced is itself immutable. 

By adding arbitrary maps they are no longer and I don't think we should do that: immutability is a very nice property we should not give up.

Also: Copying a schema is currently very cheap and safe to do (even with multiple threads involved) exactly because we have full control over the full schema graph of objects. This would also no longer be true.

I like @aschrijver suggestion to use `Map<String,String>` ... that would be perfectly and maybe it is enough for almost all use cases.

**Comment by bbakerman** [comment]
I take your point.  I am not sure Map<String,String> will do - better than none but maybe not that great.

The XXX Definition classes are not immutable BTW - in fact the parser relies on that to build them up as they parsed.  So the classes today are not immutable per se and hence hard to copy.

Also replace type reference calls on a field that is not volatile so its not thread safe to copy and technically may never be seen of the object was published across threads but the replaceTypeReference() was called later.  Thats a fix we should definitely do.

**Comment by aschrijver** [comment]
maybe grapql-java could adopt the idea of `data objects` like vertx.io does for data transfer over the event bus. they are java classes that serialize / deserialize to json..

i don't have much time to investigate further, but here is a link (vert.x can use codegen to generate java classes)

https://github.com/vert-x3/vertx-codegen/blob/master/README.md#data-objects

**Comment by kaqqao** [comment]
On the previous idea from @aschrijver , we could make a custom structure which would allow registering only immutable and/or cloneable types, similar to what annotation parameters in Java allow (plus the cloneable stuff).
So the API could be something like:
```java
metadata(String key, String metadataValue);
metadata(String key, Class<?> metadataValue);
metadata(String key, <primitives or wrappers>);
metadata(String key, <arrays of the above>);
metadata(String key, Cloneable metadataValue); //return a clone when retrieving
```
This looks like quite an overhead, but it addresses a number of concerns...

**Comment by aschrijver** [comment]
@kaqqao might not be too much overhead (ps. i linkedin msg'ed you :)

**Comment by andimarek** [comment]
this will not be included in 5.0: we need to think about it a bit more.

**Comment by bbakerman** [comment]
One other use case that I can come up with is using field meta data to feed into a complexity calculation.

That is for field X I can specify some metadata that helps me calculate field complexity.  I cant do that if I cant associate meta data or code with the field.

For example one can imagine associated helper code with a field to that might take query data as input and the meta data code does the calculation.

Or just an more complex object than String/Int which we know to be immutable.

Look I agree that Immutability is important but if some one puts metadata in the "immutable map" and changes it on the fly then its their funeral.  We can protect against them adding more data later bit not mutating the data they have.

I stronly think its ok to have nominally mutable data associated inside immutable maps.

Its always better to be useful than correct!

**Comment by bbakerman** [comment]
Closing this

**Pull request closed without merging**
