### PR TITLE
Export values as variables

### PR DESCRIPTION
**Pull request by bbakerman**
And early pull request for #807

### CODE REVIEW

**Comment by guy120494** [comment]
Does it work also with mutations? A field of the result of a mutation can be exported as a variable to a query?

**Comment by bbakerman** [comment]
I am going to see yes it works with mutations because it captures what ever output fields have @export(as:"foo") on them.

But thats a great test to add

**Comment by bbakerman** [comment]
@guy120494 - yup it works with mutations as expected.  I added a test for that case

**Comment by RyGuyOlson** [comment]
This is exciting! Do you know when this might be pulled in?

Separately, is there any coordination from any query libraries to leverage this new addition to the specification? From what I read Sangria is the only library atm that supports this functionality for batching: http://sangria-graphql.org/learn/#batch-executor

**Comment by bbakerman** [comment]
Closing as failed experiement

**Pull request closed without merging**
