### PR TITLE
Add Errorprone gradle plugin

### PR DESCRIPTION
**Pull request by siderakis**
https://errorprone.info
https://github.com/tbroyer/gradle-errorprone-plugin

This plugin configures JavaCompile tasks to use the error-prone compiler.

"We’re used to getting help from the compiler, but it doesn’t do much beyond static type checking. Using Error Prone to augment the compiler’s type analysis, you can catch more mistakes before they cost you time, or end up as bugs in production. We use Error Prone in Google’s Java build system to eliminate classes of serious bugs from entering our code, and we’ve open-sourced it, so you can too!"

### CODE REVIEW

**Comment by siderakis** [comment]
The plugin is currently showing 100 Warning. I'd be happy to go through and add start fixing issues and suppressing warning in a follow up PR.

**Comment by bbakerman** [comment]
I am happy to accept this PR - if the error prone output is too onerous we can always disable it

**Comment by bbakerman** [comment]
Its interesting that IDEA does not ship with @Overrride checks enabled

**Comment by bbakerman** [comment]
if you do submit a PR with fix ups can you please attack one problem per PR.  eg all the overrrides versus all the futures ones etc...

This will make PR review so much easier

**Comment by bbakerman** [comment]
I turned on error prone from IDEA and a large portion of the errors are @Override warnings

Hence #1096  : https://github.com/graphql-java/graphql-java/pull/1096/files

**Comment by bbakerman** [comment]
I made a bunch of these changes in prep if we ran this.

These have been merged to master.  I think you should rebase to see that final output now

**Comment by siderakis** [comment]
Nice progress :-) !

```
> Task :compileJava
/Users/siderakis/graphql/graphql-java/src/main/java/graphql/execution/ExecutionTypeInfo.java:140: warning: [JdkObsolete] Stack is a nonstandard class that predates the Java Collections Framework; prefer ArrayDeque. Note that the Stack methods push/pop/peek correspond to the Deque methods addFirst/removeFirst/peekFirst.
        Stack<GraphQLType> decoration = new Stack<>();
                                        ^
    (see http://errorprone.info/bugpattern/JdkObsolete)
/Users/siderakis/graphql/graphql-java/build/generated-src/antlr/main/graphql/parser/antlr/GraphqlParser.java:4927: warning: [MissingOverride] sempred overrides method in Recognizer; expected @Override
        public boolean sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
                       ^
    (see http://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public boolean sempred(RuleContext _localctx, int ruleIndex, int predIndex) {'?
/Users/siderakis/graphql/graphql-java/src/main/java/graphql/TypeMismatchError.java:43: warning: [DoubleBraceInitialization] Prefer collection factory methods or builders to the double-brace initialization pattern.
        private static final Map<Class<? extends GraphQLType>, Introspection.TypeKind> registry = new HashMap<Class<? extends GraphQLType>, Introspection.TypeKind>() {{
                                                                                                  ^
    (see http://errorprone.info/bugpattern/DoubleBraceInitialization)
  Did you mean 'private static final ImmutableMap<Class<? extends GraphQLType>, Introspection.TypeKind> registry = ImmutableMap.<Class<? extends GraphQLType>, Introspection.TypeKind>builder().put('?
/Users/siderakis/graphql/graphql-java/src/main/java/graphql/schema/idl/ArgValueOfAllowedTypeChecker.java:118: warning: [OrphanedFormatString] String literal contains format specifiers, but is not passed to a format method
                .orElseThrow(() -> new AssertException("Directive unknown argument type '%s'. This should have been validated before."));
                                                       ^
    (see http://errorprone.info/bugpattern/OrphanedFormatString)
/Users/siderakis/graphql/graphql-java/src/main/java/graphql/schema/idl/TypeInfo.java:29: warning: [JdkObsolete] Stack is a nonstandard class that predates the Java Collections Framework; prefer ArrayDeque. Note that the Stack methods push/pop/peek correspond to the Deque methods addFirst/removeFirst/peekFirst.
    private final Stack<Class<?>> decoration = new Stack<>();
                                               ^
    (see http://errorprone.info/bugpattern/JdkObsolete)
/Users/siderakis/graphql/graphql-java/src/main/java/graphql/schema/idl/TypeInfo.java:83: warning: [JdkObsolete] Stack is a nonstandard class that predates the Java Collections Framework; prefer ArrayDeque. Note that the Stack methods push/pop/peek correspond to the Deque methods addFirst/removeFirst/peekFirst.
        Stack<Class<?>> wrappingStack = new Stack<>();
                                        ^
    (see http://errorprone.info/bugpattern/JdkObsolete)
/Users/siderakis/graphql/graphql-java/src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java:71: warning: [FutureReturnValueIgnored] Method returns a nested type, java.util.concurrent.Future<java.util.concurrent.CompletableFuture<graphql.ExecutionResult>>
            futures.put(fieldName, executorService.submit(resolveField));
                       ^
    (see http://errorprone.info/bugpattern/FutureReturnValueIgnored)
/Users/siderakis/graphql/graphql-java/src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java:71: warning: [FutureReturnValueIgnored] Method returns a nested type, java.util.concurrent.Future<java.util.concurrent.CompletableFuture<graphql.ExecutionResult>>
            futures.put(fieldName, executorService.submit(resolveField));
                                                         ^
    (see http://errorprone.info/bugpattern/FutureReturnValueIgnored)
/Users/siderakis/graphql/graphql-java/src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java:82: warning: [FutureReturnValueIgnored] Method returns a nested type, java.util.concurrent.Future<java.util.concurrent.CompletableFuture<graphql.ExecutionResult>>
                    executionResult = futures.get(fieldName).get().join();
                                                 ^
    (see http://errorprone.info/bugpattern/FutureReturnValueIgnored)
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 warnings

```

**Comment by bbakerman** [comment]
Closing as we wont have it run day to day = we will however use it periodically to check the code

**Pull request closed without merging**
