### PR TITLE
Add visibility environment to field visibility

### PR DESCRIPTION
**Pull request by MMaas3**
pull request for #814

### CODE REVIEW

**Comment by bbakerman** [comment]
Thanks for this PR.

Wow it really became viral as to where the field visibility env needs to go.

This is a fairly big breaking change and hence needs to go into a major version 

We will have a deep look at this and see if we cant find a way to reduce the viral signature change required

**Comment by bbakerman** [comment]
Thanks for your efforts on this PR.  You have done an extensive job.

However the viral "change ALL the places" approach has been nagging at me.  Its just to much change I think.

GraphqlFieldVisibility is meant to be schema specific, that is attached to schema.  And hence your challenge of getting "query state" into the document visitors and so on.

However there is another way to have a schema that is "query" specific without all these code gymnastics.

Just transform it before use into the GraphQl object.

Lets assume your context object is the "user permissions" and hence field visibility is based on that

     GraphqlFieldVisibility fieldVisisibility = new UserPermsFieldVisisbility(getCurrentUser());

      GraphqlSchema staticSchema = getStaticSchema()

     GraphqlSchema perQuerySchema = staticSchema.transform(builder -> 
           builder.fieldVisibility(fieldVisisibility));

     GraphQL graphql = GraphQl.newGraphQL(perQueryschema).build():

     // do queries now

The above can have a static built once `GraphqlSchema` but then you transform it just before you start a query.  This transform is a shallow clone operation and super cheap.

The `new UserPermsFieldVisisbility(getCurrentUser())` would be the code that creates your per user / per request field visibility implementation.  It can do whatever logic your would have done with the "context object"

**Comment by bbakerman** [comment]
I am going to close this PR.  As stated above there is too much unintended change to get the context to the field visibility call plus I have outlined a way to achieve the same outcome.

We do really appreciate the effort you have put into this PR.  Its quality but its not the change we want to have in the code base.

**Comment by emrul** [comment]
Guys, as you know I forked off from this project a while ago since we did not have field visibility and there was some hostility towards the idea back then.  I'm glad the feature is now in but I am at a loss how you originally envisaged the field visibility to work given there is no viable way to obtain the user.  

The outlined way to achieve the same outcome is nothing less than a very poor hack - it may have been acceptable several years ago but the fact this poor design still exists is saddening.

I don't want to be overly critical of an open source effort but I am very tempted to release our fork of GraphQL Java that I've been maintaining since it seems to have better overall design choices (not to blow my own trumpet at all, but there is no way the userAccessService example here: https://www.graphql-java.com/documentation/v15/fieldvisibility/ can work and all you're doing is sending developers in ever more convoluted directions to achieve some sane behaviour.

**Pull request closed without merging**
