### PR TITLE
Implemented check for EnumValues in schema

### LINKED ISSUE #1531: Enum Values are not recognized
Hello, 

I'm using graphql-java 12 with graphql-java-tools and I have an issue: 

My schema contains something like this.
```
input MySortSpecifier {
	sortBy: SortBy = createdOn
	sortDir: SortDirection = DESC
}
enum SortBy {
	createdOn
	updatedOn
}
```
When it is loaded I get an exception that tells me this does not work:

```
graphql.schema.CoercingSerializeException: Invalid input for Enum 'SortBy'. Unknown value 'EnumValue{name='createdOn'}'
	at graphql.schema.GraphQLEnumType.getNameByValue(GraphQLEnumType.java:161) ~[graphql-java-12.0.jar:na]
	at graphql.schema.GraphQLEnumType.access$000(GraphQLEnumType.java:35) ~[graphql-java-12.0.jar:na]
	at graphql.schema.GraphQLEnumType$1.serialize(GraphQLEnumType.java:46) ~[graphql-java-12.0.jar:na]
	at graphql.language.AstValueHelper.serialize(AstValueHelper.java:212) ~[graphql-java-12.0.jar:na]
	at graphql.language.AstValueHelper.astFromValue(AstValueHelper.java:87) ~[graphql-java-12.0.jar:na]
	at graphql.introspection.Introspection.print(Introspection.java:146) ~[graphql-java-12.0.jar:na]
	at graphql.introspection.Introspection.lambda$static$1(Introspection.java:139) ~[graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:258) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:197) [graphql-java-12.0.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72) ~[graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:638) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:425) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:517) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:472) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:410) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:375) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:199) [graphql-java-12.0.jar:na]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[na:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[na:1.8.0_212]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[na:1.8.0_212]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) [graphql-java-12.0.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72) ~[graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:638) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:425) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:517) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:472) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:410) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:375) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:199) [graphql-java-12.0.jar:na]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[na:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[na:1.8.0_212]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[na:1.8.0_212]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) [graphql-java-12.0.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72) ~[graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:638) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:425) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:375) [graphql-java-12.0.jar:na]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:199) [graphql-java-12.0.jar:na]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[na:1.8.0_212]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[na:1.8.0_212]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[na:1.8.0_212]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:198) [graphql-java-12.0.jar:na]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72) ~[graphql-java-12.0.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:160) ~[graphql-java-12.0.jar:na]
	at graphql.execution.Execution.execute(Execution.java:101) ~[graphql-java-12.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:591) ~[graphql-java-12.0.jar:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:521) ~[graphql-java-12.0.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:495) ~[graphql-java-12.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:426) ~[graphql-java-12.0.jar:na]
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:92) ~[graphql-java-servlet-7.4.1.jar:na]
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:88) ~[graphql-java-servlet-7.4.1.jar:na]
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:44) ~[graphql-java-servlet-7.4.1.jar:na]
```

I have tracked the issue in this area of the code: 
`graphql.schema.GraphQLEnumType` 

```
    private Object getNameByValue(Object value) {
        for (GraphQLEnumValueDefinition valueDefinition : valueDefinitionMap.values()) {
            Object definitionValue = valueDefinition.getValue();
            if (value.equals(definitionValue)) {
                return valueDefinition.getName();
            }
            // we can treat enum backing values as strings in effect
            if (definitionValue instanceof Enum && value instanceof String) {
                if (value.equals(((Enum) definitionValue).name())) {
                    return valueDefinition.getName();
                }
            }
        }
        // ok we didn't match on pure object.equals().  Lets try the Java enum strategy
        if (value instanceof Enum) {
            String enumNameValue = ((Enum<?>) value).name();
            for (GraphQLEnumValueDefinition valueDefinition : valueDefinitionMap.values()) {
                Object definitionValue = String.valueOf(valueDefinition.getValue());
                if (enumNameValue.equals(definitionValue)) {
                    return valueDefinition.getName();
                }
            }
        }
        throw new CoercingSerializeException("Invalid input for Enum '" + name + "'. Unknown value '" + value + "'");
    }
```

From my inspection, the `value` received is an `EnumValue` so it does not match any of the checks and it fails. 

I think it should be easy to fix.

### PR DESCRIPTION
**Pull request by ieugen**
* Fixes #1531

### CODE REVIEW

**Comment by ieugen** [comment]
I made an effort and wrote the tests as I would really love to see a bugfix release for 12.0 branch. Any plans of this happening? Right now we have an internal build but it would be great to drop that and use the upstream version.

Thanks,

**Comment by bbakerman** [comment]
> I would really love to see a bugfix release for 12.0 branch. Any plans of this happening?

Sorry - our bug fix branch is 9.x - we don't have the capacity to maintain bugs branches per  releases

**Comment by ieugen** [comment]
> Sorry - our bug fix branch is 9.x - we don't have the capacity to maintain bugs branches per releases
I understand. Can I help?

**Comment by bbakerman** [comment]
For the same reasons outlined here https://github.com/graphql-java/graphql-java/pull/1533

On reflection we are reluctant to  accept this PR since its fixing a behavior of an upstream library that should not be passing AST values into enums and scalars

**Pull request closed without merging**
