### PR TITLE
Added introspection query to codebase (issue #138)

### PR DESCRIPTION
**Pull request by aschrijver**
Was a bit lazy in the unit test, not writing the full thing, but the other tests already cover individual introspection aspects, so I thought it to be all-right.

### CODE REVIEW

**Comment by aschrijver** [comment]
Build needs a check-up. It didn't run due to some socket exception.

**Comment by markphilpot** [comment]
Poked the build.  This is the same query I used for introspection so I'm glad it's a part of the project now.  Assuming the build goes through I'll merge it.

**Comment by aschrijver** [comment]
Cool :+1:

**Comment by dminkovsky** [comment]
Ditto. How did you poke it? I wasn't sure what to do.

суббота, 20 августа 2016 г. пользователь Mark Philpot написал:

**Comment by markphilpot** [comment]
Click on "Details" for the travis check
image

Click the "Redo" button in the upper right of the summary box (it's not a great UI)
image

image

**Pull request merged**
