### PR TITLE
PropertyDataFetcherHelper : take-bool-as-flow-control

### PR DESCRIPTION
**Pull request by dugenkui03**
see #1829

### CODE REVIEW

**Comment by bbakerman** [comment]
see the comments on why I am against this PR

**Comment by dugenkui03** [comment]
i have done some change about the default value of USE_NEGATIVE_CACHE,and add benchmark about flow control,details in PR

**Comment by dugenkui03** [comment]
some change:just leave "flow-control" code in PR,remove change about "USE_NEGATIVE_CACHE"

**Comment by dugenkui03** [comment]
Thanks for your review. It's my pleasure to make this PR.Yes,in most case,METHOD caching do enogh work to improve performance.

I click request review by mistake.

**Comment by bbakerman** [comment]
This PR will need to be revisted once https://github.com/graphql-java/graphql-java/pull/1815/files is merged

#1815 allows for a better cache lookup early.   Which will improve performance event more amortised across all requests.

**Comment by dugenkui03** [comment]
thanks for your review anyway

**Comment by bbakerman** [comment]
I had a local look at this PR and got the merge conflicts in place.

I also brought in the latest master code which has perf improvements

I then ran the benchmarks and the numbers seemed to be the same or slightly (very slightly) slower.

So given that the code is the same and we have 2+ years of the old proving itself out there I don't think we will take this code.  It's fine in a sense but it's not such a dramatic improvement that we will throw out battle tested code this new code.


Thanks very much for the PR - but on balance its not worth the return on investment.

**Pull request closed without merging**
