### PR TITLE
better support for Java enums

### PR DESCRIPTION
**Pull request by bbakerman**
#526 better support for Java enums by using a serialisation strategy that knows about how Java Enum<?> have unique String names

### CODE REVIEW

**Comment by bbakerman** [comment]
I think this will satisfy the principle of least suprise (when using the Schema Generator)

a java enum like

```java
        enum Episode {
            NEWHOPE,
            EMPIRE, 
            JEDI
        }
```

and a graphql type of

```graphql
            enum Episode {
                NEWHOPE,                    
                EMPIRE,
                JEDI
            }
```

should match

**Comment by andimarek** [comment]
just to make that clear: my initial solution for that was the [NaturalEnumValuesProvider](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/NaturalEnumValuesProvider.java).

The problem doesn't occur with a java schema definition because of this subtle line: ;https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/GraphQLEnumType.java#L152

**Comment by bbakerman** [comment]
The problem with using say https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/NaturalEnumValuesProvider.java  is that it doesnt satisfy the principle of least suprise

As a user of graphql I have a typed defined as an enum and then I pass back a Java object thats an enum of exactly the same shape and it does work.

I need to wire in NaturalEnumProviders for every enum I used.  And I might not have total control over all the objects and classes that are used (say in a team situation).  Assume I have 15 different enums say. I need to wire in 15 different enum providers

**Comment by bbakerman** [comment]
A thought - if we do decide that you have to provide "enum providers" (and I dont think we should) but if we do then we should enforce them at runtime wiring stage.  eg if there is a enum type then there MUST be an enum value provider

**Comment by andimarek** [comment]
@bbakerman I think it es the more convenient solution to map java enums in the core directly, so I am fine with this solution. 

Maybe we should even remove the NaturalEnumValuesProvider then, because it is basically useless.

**Pull request merged**
