### PR TITLE
Tests for Known directives validation rule

### PR DESCRIPTION
**Pull request by exbe**
* Known directives validator start using node visitor, which allows to verify type at compile time
* more tests 
* legacy directive mapping `directive.isOnXXXX()` is moved to a single method

PS
Intent behind this PR is to try out new node/graph traversal :)

### CODE REVIEW

**Comment by exbe** [comment]
1.  Do we need tests for legacy behavior? 
2. Is it a valid [case](https://github.com/graphql-java/graphql-java/pull/1008/files#diff-be0bdb1b15f4c96ee22ca21a79145100L60) or dead code?

**Comment by exbe** [comment]
Actually, I run some experiments using poor-man tool like System.nanoTime().
These 100 lines performs worse than run-time type check and deviation is significant per 1000000000 executions. 

I blame `NodeVisitor`, it restricts me to use TraverserContext, which I am instantiating per every run.
Object creation + overhead to set result overweight other benefits of using visitor here.  

So I went ahead and make a [generic node visitor](https://github.com/intuit/graphql-java/blob/fun_directives/src/main/java/graphql/language/CommonNodeVisitor.java) to check hypothesis what performance-wise visitor would take same execution cost. It looks okay at glance, but we can also run real benchmark. 

I think we can take tests from this PR and change node traversal. It should not introduce operational overhead for simple traversals like mine.

WDYT?

**Comment by bbakerman** [comment]
If you are not happy by all means re-submit in the better form

**Comment by exbe** [comment]
@bbakerman I updated PR to include tests only.

**Pull request merged**
