### PR TITLE
Support for BooleanValue in fields ins schema

### PR DESCRIPTION
**Pull request by ieugen**
This issue is very similar to #1531 . This fix adds support for BooleanValue for fields in schema files.

### CODE REVIEW

**Comment by bbakerman** [comment]
I am confused here.  graphql.language.BooleanValue is the AST node that represents a ljteral boolean value

You mention schema files here and I am guess you had problems with default values??

```
type Query {
   field( arg : Boolean = true)
```

the AST node here of true will be a BooleanValue - the schema generator turns these into actual Java objects (aka java.lang.Boolean) via co-ercing

It does make sense that Scalars.GraphqlBoolean `serialise` and `parseValue` would ever receive a AST BooleanValue node?

Can you please explain more about how you get BooleanValues into this code path??

**Comment by ieugen** [comment]
Hello @bbakerman,

I'm using graphql-java-tools via graphql-Spring-Boot 5.8.1 to parse the schema files and build the schema. I think they delegate all the work to graphql-java but I'm not familiar with that code base. 
Maybe @oliemansm  or someone from that project can help out.

I will try to make some time for the test but I am behind schedule with some projects. 

Regards,

**Comment by ieugen** [comment]
I've added some tests and pushed. Please review.

I've noticed, the parse method had tests, only the serialize method was missing them.
I think the code is very well written. It was very easy to add the missing tests.

**Comment by andimarek** [comment]
@ieugen Thanks for the PR, but I am reluctant to merge it until we know the reason for that: I don't see at the moment that this is correct behaviour as outlined by @bbakerman

**Comment by ieugen** [comment]
I understand that. For me it fixes the issues. Maybe it It's place is here, maybe in graphql-java-tools. Hopefully we will get some insight from that project. 

I did not see any stack traces to graphql-java-tools so I imagined the source is here. 

If the value is possible to appear then I think it should be covered by the serializer, otherwise maybe some code to check that these values don't get here might be in order. 

Regards,

**Comment by bbakerman** [comment]
> If the value is possible to appear then I think it should be covered by the serializer, otherwise maybe some code to check that these values don't get here might be in order.

But that kinda points to some other library doing the wrong thing.  We do not expect AST nodes to be presented to "serialise" methods since serialize methods are for Java -> graphql

So I think this is fixing whatever is causing this in the wrong place and the base library will be less correct than it should be.

I am happy to be wrong on this BTW - if we can prove that this is not the case with good reason then we would accept the PR.

I think this is the same problem as in #1532 eg AST values coming into Enum serialisation paths

**Comment by ieugen** [comment]
Yes, I agree, things should be fixed at their level. 
I wonder if validation can be improved so graphql types don't reach this point ?!
I've created an issue https://github.com/graphql-java-kickstart/graphql-java-tools/issues/276 . Hopefully someone will take a look. I'm not familiar with kotlin.

**Pull request closed without merging**
