### PR TITLE
Update FieldValidationInstrumentation.java

### PR DESCRIPTION
**Pull request by kfwerf**
Fix FieldValidationInstrumentation to forward the `state`

Fixes https://github.com/graphql-java/graphql-java/issues/3065

### CODE REVIEW

**Comment by dondonz** [comment]
Thanks! Could you also add a test that would have failed with the old behaviour, and would be fixed with your change?

**Comment by kfwerf** [comment]
Added a test for chained instrumentation

**Comment by kfwerf** [comment]
> Thanks! Could you also add a test that would have failed with the old behaviour, and would be fixed with your change?

Done! Added one for ChainedInstrumentation

**Review by Aynemayne — APPROVED** [review]

**Comment by kfwerf** [comment]
@dondonz any thoughts on this PR? We are blocked with upgrading until this gets resolved

**Review by Ekryd — APPROVED** [review]

**Review by dondonz — APPROVED** [review]
Thanks for finding the bug & writing the fix!

**Comment by dondonz** [comment]
The master build version containing this fix will be available in Maven in a few minutes. Keep in mind one change between v20 and current master was the change from Java 8 to Java 11.

FYI we usually bundle up a few PRs together for a small release, so this fix will be included in the next release. In the meantime, you can use the master build version to get unblocked now.

**Comment by kfwerf** [comment]
cool, thank you @dondonz ! Appreciate the quickness on all of this :)

**Pull request merged**
