### PR TITLE
Allow any Iterable as GraphQLList value for BatchedExecutionStrategy

### LINKED ISSUE #667: Remove unnecessary limitation regarding BatchedExecutionStrategy and GraphQLList types
On [BatchedExecutionStrategy.java#L204](https://github.com/graphql-java/graphql-java/blob/02f34e6f870395332bb3c1819b0f3914f76e0a3a/src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java#L204) DataFetcher return value is cast to Java `List<Object>`, which I feel is an unnecessary restriction, as it is merely iterated over. Instead, value should be cast to `Collection<?>` (or even `Iterable<?>`?).

I haven't checked if other build-in execution strategies have the same restriction, but if they do, the above also applied to them.

Thoughts?

### PR DESCRIPTION
**Pull request by arlampin**
Fixes #667

### CODE REVIEW

**Comment by hepin1989** [comment]
And Array:)

**Comment by bbakerman** [comment]
https://github.com/graphql-java/graphql-java/pull/679 will allow arrays returned and tweaks the error messages a little better

**Comment by arlampin** [comment]
That's another issue, I was talking about `BatchedExecutionStrategy.handleList()`, not overall `BatchedDataFetcher` return type.

**Comment by arlampin** [comment]
I updated PR to use the exact same logic as regular ExecutionStrategy, which supports arrays (and also primitive arrays after #681 has been merged)

**Comment by bbakerman** [comment]
I have updated https://github.com/graphql-java/graphql-java/pull/679 with the contents of this PR and its extra test

**Pull request closed without merging**
