### PR TITLE
DataFetchingEnvironment generic methods accept Class<T> as an argument

### PR DESCRIPTION
**Pull request by guy120494**
see issue #328

### CODE REVIEW

**Comment by dminkovsky** [comment]
@bbakerman what do you think?

**Comment by dminkovsky** [comment]
Thank you @guy120494

**Comment by dminkovsky** [comment]
By the way, I thought it about it some more and I'm not really sure this will improve compile-type safety. Does it actually?

**Comment by guy120494** [comment]
well, Im not a java expert (yed :P ) but I think it is.
lets say that getSource suppose to return Integer.
String s = env.getSource(); - compiles but we get ClassCastException
String s  =env.getSource(Integer.class) - doesnt compile

**Comment by dminkovsky** [comment]
That's correct but what it's checking there is that the right and left side
match. At runtime if cast fails, you still get a class cast exception.

Not a java expert either, and I think that's why I was confused about this
at first! But I think my current understanding is correct.

чт, 16 февр. 2017 г. в 14:47, Guy Smorodinsky <notifications@github.com>:

well, Im not a java expert (yed :P ) but I think it is.
lets say that getSource suppose to return Integer.
String s = env.getSource(); - compiles but we get ClassCastException
String s =env.getSource(Integer.class) - doesnt compile

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/graphql-java/graphql-java/pull/329#issuecomment-280438394>,
or mute the thread

**Comment by guy120494** [comment]
that's true, and I think that this is better than nothing, because its sometimes can prevent confusion.
Worst case scenario, it does no harm

**Comment by bbakerman** [comment]
I don't this this offers enough real value while making the DateFetcherEnvironment fiddlier to use

      <T> T getSource();

     <T> T getSource(Class<T> type);

The really end up being the same.  That is if the source is NOT a <T> then you will get a class cast exception at runtime.

I can see a small argument for better "compile time" protection but really since you have to assigned the left hand side to some type you are all ready telling the compiler what you know (as a human) the type you want.

So as a programmer if I write

  Foo foo = env.getSource() 

then I am encoding that the value is expected to be  of type Foo and if its not an exception swill be thrown latter.  So writing

  Foo foo = env.getSource(Foo.class) 

does not get me anything really.  It MUST be a Foo on the left hand side.  The implementation here is

    public <T> T getSource(Class<T> type) {
        return type.cast(source);
      }

which is defined as

    Casts this Class object to represent a subclass of the class represented by the specified class     
    object. Checks that that the cast is valid, and throws a ClassCastException if it is not. If this 
    method succeeds, it always returns a reference to this class object.

So its throws a ClasscastException - same diff and yet we had to write 

    T t = env.getSource(T.class)

So more code for the same effect.

I would not like to accept this PR.  It does not offer enough benefit and makes the API that much fiddlier to work with.

We want people to submit PRs so thank you for doing that, but I cannot recommend that this API change be accepted.

That said if you can offer strong uses cases where this really helps, please outline them

**Pull request closed without merging**
