### PR TITLE
Add InstrumentationValidationParameters to QueryComplexityInfo

### PR DESCRIPTION
**Pull request by stevenleeDB**
Addressing #2547

### CODE REVIEW

**Review by bbakerman — APPROVED** [review]
Thanks for this PR.

I had a concern that the raw parameters would to "wide" but given that `MaxQueryComplexityInstrumentation` is an instrumentation anyway, giving access to the validtion parameters is ok

**Comment by stevenleeDB** [comment]
@bbakerman thanks! Would you be able to merge this for me?

**Comment by softprops** [comment]
any word on when the next release will be that would include these changes?

**Comment by bbakerman** [comment]
Every merge to master results in a timestamped release of graphql-java in
Maven central

So you can update if you need to.

As for the release, we havent convened to decide when - Typically its every
6 months or so but...that is not set in stone

**Pull request merged**
