### PR TITLE
minor cleanups

### PR DESCRIPTION
**Pull request by dfa1**
- dropping some vestigial warning suppressions
- dropping few unused imports
- simplifying some Objects.equals implementations
- using of diamond operator
- improving javadoc

### CODE REVIEW

**Comment by andimarek** [comment]
Looks good, but it has now merge conflicts unfortunately

**Comment by dfa1** [comment]
merge conflict merged

**Comment by dfa1** [comment]
hi @andimarek, 

please have another look here :)

**Comment by bbakerman** [comment]
Sorry this got lost

**Comment by dfa1** [comment]
@bbakerman  no worries :)

**Pull request closed without merging**
