### PR TITLE
[WIP - DO NOT MERGE] Add CI/CD for Java `{8, 11, 17, 18} x {HotSpot, OpenJ9}`, fix tests

### LINKED ISSUE #2676: Run CI on more recent Java versions and different runtimes
There should probably be tests for on more recent builds of OpenJDK v8, LTS 11, and LTS 17. Potentially even on JDK (pre-release) 18 
and the OpenJ9 (and GraalVM runtimes).

If there is support, I have time at the end of next week to contribute this. Let me know 😃 .

### PR DESCRIPTION
**Pull request by jord1e**
Closes #2676

# 🚧 WIP - DO NOT MERGE

### CODE REVIEW

**Comment by andimarek** [comment]
quick general feedback: please create seperate PRs for different kind of things. For example if we need to update some libraries, lets do that in another PRs, etc. 

thanks a lot

**Comment by jord1e** [comment]
> quick general feedback: please create seperate PRs for different kind of things. For example if we need to update some libraries, lets do that in another PRs, etc.
> 
> thanks a lot

Will do

**Comment by jord1e** [comment]
Closing whilst I am working in https://github.com/jord1e/graphql-java/pull/1

**Comment by jord1e** [comment]
Superseded by #2789

**Pull request closed without merging**
