### PR TITLE
Support in DataFetchingFieldSelectionSet for Unions and Interfaces

### PR DESCRIPTION
**Pull request by bbakerman**
This improves the DataFetchingFieldSelectionSet support so that conditional composite types such as Unions can now be supported.

Its a breaking change because we can now get multiple `SelectedField`s in for a given addressing name.  Therefore `getField` no longer makes sense nor do the maps to 1:1 arguments and field definitiions

This supersedes the PR #1963

### CODE REVIEW

**Comment by bbakerman** [comment]
graphql.schema.DataFetcherSelectionTest still needs to be fixed

**Review by bbakerman — COMMENTED** [review]
I think this is now ready for review

**Comment by jhaals** [comment]
@bbakerman thanks for improving the PR. 

Here are some things that are problematic.
`dataFetchingEnvironment.getSelectionSet().getFields()` returns duplicates of each field.

Overall this has reduced the custom code we need thanks to the ability to find fields with `DataFetchingFieldSelectionSet.getFields(String)`.

We noticed that the transitive nature of `DataFetchingFieldSelectionSet` causes issues sometimes. We need a way to get only the fields nested directly under the current field. Right now we tried using the `getObjectType()` of the fields in the selection set to filter out any fields we're not interested in, but this doesn’t work when the same type is nested recursively in itself.


```graphql
type User {
  name: String
  address: String
  friend: User
}

{
  user(id: "steve") {
    name
    friend {
      name
      address
    }
  }
}
```

The selection set for the user query would contain all fields (also the nested ones) and if we try to use the type to tell which fields to take, we end up with [name, friend, address] when what we really want is to be able to tell the two “users” apart and have [name, friend] and later [name, address].

**Comment by bbakerman** [comment]
@jhaals - see https://github.com/graphql-java/graphql-java/pull/2079/commits/6401f124bf5d726f4cf04fcd7129b56d49c685b9

I have added a getImmediateFields() method

**Comment by jhaals** [comment]
@bbakerman We've switched to using `getImmediateFields()` and it works great 💯

**Review by jhaals — APPROVED** [review]

**Comment by jhaals** [comment]
@bbakerman @andimarek another friendly ping about this PR. Are there any leftovers or things we can do or help out with in order to get this PR merged? We really need union support in graphql-java 🙏

**Review by andimarek — APPROVED** [review]

**Pull request merged**
